parameters:
  # Target speed parameter sweep
  target_speed:
    type: linear
    min: 0.3
    max: 1.2
    steps: 5
    description: "Vehicle target speed in m/s"
    
  # MPC horizon length  
  horizon_length:
    type: discrete
    values: [6, 8, 10, 12, 15, 20]
    description: "MPC prediction horizon length"
    
  # Control time step
  control_dt:
    type: discrete
    values: [0.05, 0.1, 0.15, 0.2]
    description: "MPC control time step in seconds"
    
  # Position tracking weight (Q matrix)
  position_weight:
    type: logarithmic
    min: 1.0
    max: 100.0
    steps: 5
    description: "Position tracking weight in MPC cost function"
    
  # Yaw tracking weight (Q matrix)
  yaw_weight:
    type: logarithmic  
    min: 1.0
    max: 100.0
    steps: 5
    description: "Yaw tracking weight in MPC cost function"
    
  # Control cost weight (R matrix)
  control_weight:
    type: logarithmic
    min: 0.01
    max: 10.0
    steps: 4
    description: "Control cost weight in MPC cost function"
    
  # Maximum steering angle
  max_steer_deg:
    type: linear
    min: 5.0
    max: 20.0
    steps: 4
    description: "Maximum steering angle in degrees"
    
  # N_IND_SEARCH parameter
  lookahead_distance:
    type: discrete
    values: [10, 20, 30, 50]
    description: "Path lookahead search distance"

# Evaluation metrics to analyze
evaluation_metrics:
  - position_errors
  - heading_errors
  - cross_track_errors
  - control_effort
  - control_smoothness
  - path_progress
  - velocity_errors

# Experiment settings
experiment_settings:
  warmup_time: 5.0      # Time to let system stabilize
  evaluation_time: 50.0  # Main evaluation period
  cooldown_time: 5.0     # Time to safely shutdown
  
# Analysis settings
analysis_settings:
  statistical_significance: 0.05
  correlation_threshold: 0.3
  improvement_threshold: 5.0  # Minimum % improvement to be significant