parameters:
  # Target speed - focus on practical range
  target_speed:
    type: discrete
    values: [0.5, 0.8, 1.1]
    description: "Vehicle target speed in m/s - slow, medium, fast"
    
  # MPC horizon length - test key values
  horizon_length:
    type: discrete
    values: [8, 12, 16]
    description: "MPC prediction horizon length - short, medium, long"
    
  # Control time step - critical for stability
  control_dt:
    type: discrete
    values: [0.05, 0.1]
    description: "MPC control time step - fine vs coarse control"
    
  # Position tracking weight - most impactful parameter
  position_weight:
    type: discrete
    values: [5.0, 15.0, 40.0]
    description: "Position tracking weight - low, medium, high priority"
    
  # Yaw tracking weight - critical for path following
  yaw_weight:
    type: discrete
    values: [5.0, 20.0, 50.0]
    description: "Yaw tracking weight - loose, balanced, tight heading"
    
  # Control cost weight - affects smoothness vs performance
  control_weight:
    type: discrete
    values: [0.1, 0.5]
    description: "Control cost weight - aggressive vs smooth control"
    
  # Maximum steering angle - vehicle constraint
  max_steer_deg:
    type: discrete
    values: [10.0, 15.0]
    description: "Maximum steering angle - conservative vs aggressive"
  # Path selection - only YAML and switch_back paths
  path_type:
    type: discrete
    values: ["yaml", "switch_back"]
    description: "Path types - YAML file path or challenging switch-back maneuvers"

# Evaluation metrics to analyze
evaluation_metrics:
  - position_errors
  - heading_errors
  - cross_track_errors
  - control_effort
  - control_smoothness
  - path_progress
  - velocity_errors

# Experiment settings - reduced timing for faster testing
experiment_settings:
  warmup_time: 1.0      # Reduced warmup
  evaluation_time: 20.0  # Much shorter evaluation for testing
  cooldown_time: 1.0     # Minimal cooldown
  
# Analysis settings
analysis_settings:
  statistical_significance: 0.05
  correlation_threshold: 0.3
  improvement_threshold: 5.0