parameters:
  # Target speed - reduced values for testing
  target_speed:
    type: discrete
    values: [0.5, 0.8]  # Reduced from 3 to 2 values
    description: "Vehicle target speed in m/s - slow, medium"
    
  # MPC horizon length - reduced values
  horizon_length:
    type: discrete
    values: [8, 12]  # Reduced from 3 to 2 values
    description: "MPC prediction horizon length - short, medium"
    
  # Control time step - keep minimal
  control_dt:
    type: discrete
    values: [0.1]  # Reduced to 1 value for faster testing
    description: "MPC control time step - standard"
    
  # Position tracking weight - reduced values
  position_weight:
    type: discrete
    values: [5.0, 15.0]  # Reduced from 3 to 2 values
    description: "Position tracking weight - low, medium priority"
    
  # Yaw tracking weight - reduced values  
  yaw_weight:
    type: discrete
    values: [5.0, 20.0]  # Reduced from 3 to 2 values
    description: "Yaw tracking weight - loose, balanced heading"
    
  # Control cost weight - keep minimal
  control_weight:
    type: discrete
    values: [0.1]  # Reduced to 1 value
    description: "Control cost weight - standard"
    
  # Maximum steering angle - keep minimal
  max_steer_deg:
    type: discrete
    values: [10.0]  # Reduced to 1 value
    description: "Maximum steering angle - standard"
    
  # Path selection - only YAML and switch_back paths
  path_type:
    type: discrete
    values: ["yaml", "switch_back"]
    description: "Path types - YAML file path or challenging switch-back maneuvers"

# Evaluation metrics to analyze
evaluation_metrics:
  - position_errors
  - heading_errors
  - cross_track_errors
  - control_effort
  - control_smoothness
  - path_progress
  - velocity_errors

# Experiment settings - reduced timing for faster testing
experiment_settings:
  warmup_time: 1.0      # Reduced warmup
  evaluation_time: 20.0  # Much shorter evaluation for testing
  cooldown_time: 1.0     # Minimal cooldown
  
# Analysis settings
analysis_settings:
  statistical_significance: 0.05
  correlation_threshold: 0.3
  improvement_threshold: 5.0