controller_manager:
  ros__parameters:
    update_rate: 1000
    steering_controller:
      type: position_controllers/JointGroupPositionController
    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

steering_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - left_steering_hinge_wheel
      - right_steering_hinge_wheel

velocity_controller:
  ros__parameters:
    use_sim_time: true
    joints:
      - rear_left_wheel
      - rear_right_wheel

